### ISSUE TITLE
Generic Expression error in Magswitch script

### ISSUE THREAD

**Issue by toadie2k** [toadie2k/NIArms#97]
Putting it here for accounting's sake - something's up in the magswitch script, around the _ammo argument it's pulling a generic expression error. Apparently that is enough to trip ACE up.
Error in expression <onMuzzle, [currentMagazine _unit, _unit ammo _weaponMuzzle]] call Niarms_fnc_mag>
Error position: <ammo _weaponMuzzle]] call Niarms_fnc_mag>

**Comment by toadie2k** [comment]
commenting out `_unit ammo` seems to have done the trick. Functionality seems to have not broken, the but the error's gone, not being spammed to logs, and ACE interact doesn't break, so I'm assuming that bit was extraneous. 

If this is wrong, please scream at me and I'll reopen and find more solutions.

**Comment by robalo** [comment]
Actual error found on forums:
22:50:26   Error position: <ammo _weaponMuzzle]] call Niarms_fnc_mag>
22:50:26   Error ammo: Type Nombre, Chaîne attendu
translates to: Type Number, Expected String

The only case documented on BIKI where [currentMuzzle](https://community.bistudio.com/wiki/currentMuzzle) would return number instead of string would be when it's used with a vehicle instead of a person. Which is weird because we do it with XEH on class CAManBase. Maybe documentation is incomplete, maybe it happens when the unit starts inside a vehicle.
Working on a patch.

**Comment by toadie2k** [comment]
```
13:13:42 File \hlc_core\functions\fnc_magInit.sqf [Niarms_fnc_magInit], line 16
13:13:42 Error in expression <his, _cm, [currentMagazine _this, _this ammo _cm]] call Niarms_fnc_magSwitch},
_>
13:13:42   Error position: <ammo _cm]] call Niarms_fnc_magSwitch},
_>
13:13:42   Error ammo: Type Number, expected String
```
Reopening. Built off latest commit, Change of form, same error.

**Comment by toadie2k** [comment]
To reproduce- 
- Virtual Garage/Arsenal
- Select a vehicle, load crew
- unselect crew

**Comment by tupolov** [comment]
Assuming `_this` is pointing at an infantry unit, can you change 

`{isNull objectParent _this}`

to

`{vehicle _this == _this}`

**Comment by jokoho48** [comment]
why isNull objectParent obj is faster then vehicle obj == obj

**Comment by tupolov** [comment]
Seems like that check doesn't work if currentMuzzle is returning an integer - which suggests the unit is still in a vehicle. objectParent may be faster, but does it actually work in this scenario?

**Comment by dedmen** [comment]
Why doesn't it work when unit is in a vehicle? 
https://community.bistudio.com/wiki/currentMuzzle
Says the problem is only when you give it a vehicle. How about just not doing that and giving it the actual unit?

Or is the warning on the wiki an error and it should say `will return number if given object is IN a vehicle` instead of `is a vehicle`.

Could you maybe just log `_this` and see what it actually contains at the time of the error? That way we know if the check is actually failing (Additonally log `objectParent` and `vehicle _this`). Because it could very well be that the check is working but BI is messing something up on their end. As I said the error doesn't even make sense according to the warning on Biki so maybe it's not a good idea trusting that.

Here is the script file for further reference btw: https://github.com/toadie2k/NIArms/blob/master/hlc_core/functions/fnc_magInit.sqf

**Comment by dedmen** [comment]
Checked the currentMuzzle function. Wiki is indeed not correct enough.

Returns 0 if unit is not a person, if unit doesn't have a AI Brain, if unit doesn't have AI (All Player units have AI), if unit doesn't have a Turret (This one is important).
Returns empty string if the current weapon of the found turret is incorrect. As in Weapon in slot 5 is currently selected but only 2 slots exist.
Returns empty string if the weapon doesn't have a muzzle (I guess you can do that with config editing?)
Otherwise returns muzzle name.

I guess it's failing at finding the Turret. Maybe there are one or more frames when you just got out of a vehicle that you are kinda out of the vehicle. But not that out of it that you have your turret back.

I don't see why you can't just use it on the unit object while it is inside a vehicle. Except if the Unit looses it's Turret when in a vehicle. And if that's the case then it sounds not too far off that a unit might not yet have his Turret back when it is in the middle of leaving a vehicle.

**Comment by dedmen** [comment]
Oops sorry. Overlooked something. 
The turret check fails always if the unit's vehicle (`vehicle _unit`) is != `_unit`.
`if unit doesn't have AI` is wrong. It get's the unit's vehicle which is always a AI (Vehicles are also AI's). It then tries to find the vehicles turret that is used by the unit.
On an actual vehicle that's fine. It checks all the weapons in the vehicle till it finds the one that's occupied by the unit and uses that.
On a unit however. It does if vehicle != unit then return false. Because a unit can't have another unit inside of it that's different from itself.

So yes. The wiki is incorrect. `is IN a vehicle` would be correct. And they use the `vehicle _unit` equivalent internally. I'll fix that immediatly.

Just confirmed `vehicle _unit` is using the same logic as `currentMuzzle`. I don't have objectParent on hand right now to check.

**Comment by robalo** [comment]
Thanks for the analysis guys. Here are my observations after testing Toadie's scenario:
When you delete the crew, looks like the unit first gets unassigned then deleted. So it kind of lives outside the vehicle for some microseconds before it gets deleted:

diag_log format ["Unit: %1, objectParent: %2, currentMuzzle: %3, vehicle: %4", _unit, objectParent _unit, currentMuzzle _unit, vehicle _unit];
21:14:22 "Unit: 1697b59ad00# 11: b_soldier_03.p3d, objectParent: <NULL-object>, currentMuzzle: 0, vehicle: 1697b59ad00# 11: b_soldier_03.p3d"

I am thinking that using CBA_fnc_waitUntilAndExecute in this case might have not been the best idea.

**Comment by robalo** [comment]
The idea was to reuse the same function for the reloaded EH in the init EH.
This required passing the same parameters when called from init.
Passing the current muzzle of held weapon and the ammo count proved difficult (I dare not say impossible) for units inside vehicles.
So I think maybe I'll just use separate code for init and just parse magazinesAmmoFull to get the loadout and replace stuff and that will work inside vehicles too.
